// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type AliasInfo struct {
	UUID          string              `json:"uuid"`
	Enabled       string              `json:"enabled"`
	Name          string              `json:"name"`
	Type          string              `json:"type"`
	TypeName      string              `json:"%type"`
	Proto         string              `json:"proto"`
	Interface     string              `json:"interface"`
	Counters      string              `json:"counters"`
	UpdateFreq    string              `json:"updatefreq"`
	Content       string              `json:"content"`
	Password      string              `json:"password"`
	Username      string              `json:"username"`
	AuthType      string              `json:"authtype"`
	Expire        string              `json:"expires"`
	Categories    api.SelectedMapList `json:"categories"`
	CategoryNames api.SelectedMapList `json:"%categories"`
	LastUpdated   string              `json:"last_updated"`
	EvalNoMatch   string              `json:"eval_nomatch"`
	EvalMatch     string              `json:"eval_match"`
	InBlockP      string              `json:"in_block_p"`
	InBlockB      string              `json:"in_block_b"`
	InPassP       string              `json:"in_pass_p"`
	InPassB       string              `json:"in_pass_b"`
	OutBlockP     string              `json:"out_block_p"`
	OutBlockB     string              `json:"out_block_b"`
	OutPassP      string              `json:"out_pass_p"`
	OutPassB      string              `json:"out_pass_b"`
	Description   string              `json:"description"`
	CategoryUUID  []string            `json:"categories_uuid"`
}

type AliasesResponse struct {
	Total    int         `json:"total"`
	RowCount int         `json:"rowCount"`
	Current  int         `json:"current"`
	Aliases  []AliasInfo `json:"rows"`
}

// AliasesGet executes the Get RPC call of the Aliases controller
func (c *Controller) AliasesGet(ctx context.Context) (*AliasesResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/alias/search_item",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &AliasesResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}
