// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type CategoriesResponse struct {
	Total      int            `json:"total"`
	RowCount   int            `json:"rowCount"`
	Current    int            `json:"current"`
	Categories []CategoryInfo `json:"rows"`
}

type CategoryInfo struct {
	UUID  string `json:"uuid"`
	Name  string `json:"name"`
	Auto  string `json:"auto"`
	Color string `json:"color"`
}

// CategoriesGet executes the Get RPC call of the Categories controller
func (c *Controller) CategoriesGet(ctx context.Context) (*CategoriesResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/firewall/category/search_item",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &CategoriesResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}
