// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type DNATInfo struct {
	UUID                   string               `json:"uuid"`
	Sequence               string               `json:"sequence"`
	Disabled               string               `json:"disabled"`
	NoRDR                  string               `json:"nordr"`
	Interface              string               `json:"interface"`
	InterfaceName          string               `json:"%interface"`
	IPProtocol             string               `json:"ipprotocol"`
	IPProtocolName         string               `json:"%ipprotocol"`
	Protocol               string               `json:"protocol"`
	ProtocolName           string               `json:"%protocol"`
	SourceNetwork          string               `json:"source.network"`
	SourceAddress          string               `json:"source.address"`
	SourcePort             string               `json:"source.port"`
	SourceInvert           string               `json:"source.not"`
	DestinationNetwork     string               `json:"destination.network"`
	DestinationNetworkName string               `json:"%destination.network"`
	DestinationAddress     string               `json:"destination.address"`
	DestinationPort        string               `json:"destination.port"`
	DestinationInvert      string               `json:"destination.not"`
	Target                 string               `json:"target"`
	LocalPort              string               `json:"local-port"`
	PoolOpts               string               `json:"poolopts"`
	Log                    string               `json:"log"`
	Category               api.SelectedMapList  `json:"category"`
	CategoryNames          api.SelectedMapList  `json:"%category"`
	Categories             api.SelectedMapList  `json:"categories"`
	Description            string               `json:"descr"`
	SetTag                 string               `json:"tag"`
	MatchTag               string               `json:"tagged"`
	NoXMLRPCSync           string               `json:"nosync"`
	NATReflection          string               `json:"natreflection"`
	Pass                   string               `json:"pass"`
	PassName               string               `json:"%pass"`
	AssociatedRuleID       string               `json:"associated-rule-id"`
	CreatedByUsername      string               `json:"created.username"`
	CreatedAt              string               `json:"created.time"`
	CreatedDescription     string               `json:"created.description"`
	UpdatedByUsername      string               `json:"updated.username"`
	UpdatedAt              string               `json:"updated.time"`
	UpdatedDescription     string               `json:"updated.description"`
	CategoryColors         []RuleCategoryColors `json:"category_colors"`
	DestinationAliasMeta   []RuleAliasMeta      `json:"alias_meta_destination.network""`
	DestinationPortMeta    []RuleAliasMeta      `json:"alias_meta_destination.port"`
	TargetAliasMeta        []RuleAliasMeta      `json:"alias_meta_target"`
	LocalPortMeta          []RuleAliasMeta      `json:"alias_meta_local-port"`
}

type DNATResponse struct {
	Total    int        `json:"total"`
	RowCount int        `json:"rowCount"`
	Current  int        `json:"current"`
	DNATs    []DNATInfo `json:"rows"`
}

// DestinationNATGet executes the Get RPC call of the DestinationNAT controller
func (c *Controller) DestinationNATGet(ctx context.Context) (*DNATResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/firewall/d_nat/search_rule",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &DNATResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}
