// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type RuleInfo struct {
	UUID                     string               `json:"uuid"`
	Enabled                  string               `json:"enabled"`
	StateType                api.SelectedMap      `json:"statetype"`
	StateTypeName            api.SelectedMap      `json:"%statetype"`
	StatePolicy              api.SelectedMap      `json:"state-policy"`
	Sequence                 string               `json:"sequence"`
	SortOrder                string               `json:"sort_order"`
	PriorityGroup            string               `json:"prio_group"`
	Action                   api.SelectedMap      `json:"action"`
	Quick                    string               `json:"quick"`
	InvertInterface          string               `json:"interfacenot"`
	Interface                api.SelectedMapList  `json:"interface"`
	InterfaceName            api.SelectedMapList  `json:"%interface"`
	Direction                api.SelectedMap      `json:"direction"`
	DirectionName            api.SelectedMap      `json:"%direction"`
	IPProtocol               api.SelectedMap      `json:"ipprotocol"`
	IPProtocolName           api.SelectedMap      `json:"%ipprotocol"`
	Protocol                 api.SelectedMap      `json:"protocol"`
	ICMPType                 api.SelectedMapList  `json:"icmptype"`
	ICMP6Type                api.SelectedMapList  `json:"icmp6type"`
	SourceNet                string               `json:"source_net"`
	SourceNetName            string               `json:"source_net"`
	SourceInvert             string               `json:"source_not"`
	SourcePort               string               `json:"source_port"`
	DestinationNet           string               `json:"destination_net"`
	DestinationInvert        string               `json:"destination_not"`
	DestinationPort          string               `json:"destination_port"`
	DivertTo                 string               `json:"divert-to"`
	DivertToName             string               `json:"%divert-to"`
	Gateway                  api.SelectedMap      `json:"gateway"`
	ReplyTo                  api.SelectedMap      `json:"replyto"`
	DisableReplyTo           string               `json:"disablereplyto"`
	Log                      string               `json:"log"`
	AllowOptions             string               `json:"allowopts"`
	NoXMLRPCSync             string               `json:"nosync"`
	NoPfsync                 string               `json:"nopfsync"`
	StateTimeout             string               `json:"statetimeout"`
	UDPFirst                 string               `json:"udp-first"`
	UDPMultiple              string               `json:"udp-multiple"`
	UDPSingle                string               `json:"udp-single"`
	MaxSourceNodes           string               `json:"max-src-nodes"`
	MaxSourceStates          string               `json:"max-src-states"`
	MaxSourceConnections     string               `json:"max-src-conn"`
	MaxStates                string               `json:"max"`
	MaxNewConnectionsCount   string               `json:"max-src-conn-rate"`
	MaxNewConnectionsSeconds string               `json:"max-src-conn-rates"`
	OverloadTable            api.SelectedMap      `json:"overload"`
	AdaptiveTimeoutsStart    string               `json:"adaptivestart"`
	AdaptiveTimeoutsEnd      string               `json:"adaptiveend"`
	MatchPriority            api.SelectedMap      `json:"prio"`
	SetPriority              api.SelectedMap      `json:"set-prio"`
	SetPriorityLowDelay      api.SelectedMap      `json:"set-prio-low"`
	SetLocalTag              string               `json:"tag"`
	MatchLocalTag            string               `json:"tagged"`
	TCPFlags                 api.SelectedMapList  `json:"tcpflags1"`
	TCPFlagsOutOf            api.SelectedMapList  `json:"tcpflags2"`
	TCPFlagsAny              string               `json:"tcpflags_any"`
	Categories               api.SelectedMapList  `json:"categories"`
	CategoriesNames          api.SelectedMapList  `json:"%categories"`
	Schedule                 api.SelectedMap      `json:"sched"`
	MatchTOS                 api.SelectedMap      `json:"tos"`
	TrafficShaper            api.SelectedMap      `json:"shaper1"`
	TrafficShaperReverse     api.SelectedMap      `json:"shaper2"`
	Description              string               `json:"description"`
	SourceAliasMeta          []RuleAliasMeta      `json:"alias_meta_source_net"`
	SourcePortMeta           []RuleAliasMeta      `json:"alias_meta_source_port"`
	DestinationAliasMeta     []RuleAliasMeta      `json:"alias_meta_destination_net"`
	DestinationPortMeta      []RuleAliasMeta      `json:"alias_meta_destination_port"`
	CategoryColors           []RuleCategoryColors `json:"category_colors"`
}

type RulesInfoResponse struct {
	Total    int        `json:"total"`
	RowCount int        `json:"rowCount"`
	Current  int        `json:"current"`
	Rules    []RuleInfo `json:"rows"`
}

// RulesGet executes the Get RPC call of the Rules controller
func (c *Controller) RulesGet(ctx context.Context) (*RulesInfoResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/firewall/filter/search_rule",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &RulesInfoResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}
