// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var SharedOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "",
	UpdateEndpoint:      "",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: "",
	Monad:               "",
}

// Data structs

type RuleAliasMeta struct {
	Value       string `json:"value"`
	Name        string `json:"%value"`
	IsAlias     bool   `json:"isAlias"`
	Description string `json:"description"`
	Summary     string `json:"summary"`
}

type RuleCategoryColors struct {
	Color string `json:"color"`
	Name  string `json:"name"`
	UUID  string `json:"uuid"`
}

type Shared struct {
}

// CRUD operations

func (c *Controller) GetShared(ctx context.Context, id string) (*Shared, error) {
	return api.Get(c.Client(), ctx, SharedOpts, &Shared{}, id)
}
